use crate::error::ArchonError;
use ed25519_dalek::{SigningKey, VerifyingKey, Signer, Verifier, Signature};
use zeroize::{Zeroize, ZeroizeOnDrop};

// WHY: External JS function to extract hardware entropy from expo-secure-store in mobile app
#[cfg(target_arch = "wasm32")]
use wasm_bindgen::prelude::*;

#[cfg(target_arch = "wasm32")]
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_name = generate_secure_random)]
    fn js_generate_secure_random(len: u32) -> Vec<u8>;
}

// WHY: Zeroize is used to scrub secret keys from memory once they go out of scope.
#[derive(Zeroize, ZeroizeOnDrop)]
pub struct Identity {
    secret_bytes: [u8; 32],
    #[zeroize(skip)]
    signing_key: SigningKey,
}

impl Identity {
    // WHY: Generates a new identity keypair using secure host entropy on wasm, or thread_rng on native
    pub fn generate() -> Result<Self, ArchonError> {
        let mut entropy = [0u8; 32];
        
        #[cfg(target_arch = "wasm32")]
        {
            let random_bytes = js_generate_secure_random(32);
            if random_bytes.len() != 32 {
                return Err(ArchonError::Auth("Failed to get 32 bytes of secure entropy from host".to_string()));
            }
            entropy.copy_from_slice(&random_bytes);
        }
        
        #[cfg(not(target_arch = "wasm32"))]
        {
            use rand::RngCore;
            rand::thread_rng().fill_bytes(&mut entropy);
        }

        let signing_key = SigningKey::from_bytes(&entropy);
        
        Ok(Self {
            secret_bytes: entropy,
            signing_key,
        })
    }

    pub fn secret_bytes(&self) -> &[u8; 32] {
        &self.secret_bytes
    }

    // WHY: Signs messages using the Ed25519 private key
    pub fn sign(&self, message: &[u8]) -> Vec<u8> {
        let signature = self.signing_key.sign(message);
        signature.to_bytes().to_vec()
    }

    // WHY: Exposes the public key for zero-trust client registry
    pub fn public_key_bytes(&self) -> [u8; 32] {
        self.signing_key.verifying_key().to_bytes()
    }

    // WHY: Derives a 32-byte vault encryption key from the identity secret seed using SHA3-256
    pub fn derive_vault_key(&self) -> [u8; 32] {
        use sha3::{Digest, Sha3_256};
        let mut hasher = Sha3_256::new();
        hasher.update(&self.secret_bytes);
        let mut key = [0u8; 32];
        key.copy_from_slice(&hasher.finalize());
        key
    }

    // WHY: Verify signatures generated by the twin
    pub fn verify(signature_bytes: &[u8], message: &[u8], public_key_bytes: &[u8]) -> bool {
        let Ok(verifying_key_bytes) = <[u8; 32]>::try_from(public_key_bytes) else {
            return false;
        };
        let Ok(verifying_key) = VerifyingKey::from_bytes(&verifying_key_bytes) else {
            return false;
        };
        let Ok(sig_bytes) = <[u8; 64]>::try_from(signature_bytes) else {
            return false;
        };
        let signature = Signature::from_bytes(&sig_bytes);
        
        verifying_key.verify(message, &signature).is_ok()
    }

    #[cfg(feature = "pqc")]
    pub fn generate_dilithium() -> Result<Vec<u8>, ArchonError> {
        // Mock PQC signature keypair generation when compiled with liboqs PQC target feature
        Ok(vec![9, 8, 7, 6, 5, 4, 3, 2, 1])
    }
}

